### ISSUE TITLE
Looking for a way to run this at build time in nextjs

### ISSUE THREAD

**Issue by arunavo4** [fabian-hiller/og-img#4]
I have a usecase where I have a small blog and I dont want to generate the images at runtime. I would like to run this at build time.

**Comment by fabian-hiller** [comment]
You could do this with a custom pre- and post-build step that starts your web server, grabs all the images, rewrites the image paths, bundles your site, and then restores the image paths. But that is probably nothing this package can do for you because every project if different. Maybe there is a Next.js image component that can do this. I know there is one for Nuxt.js.

**Comment by arunavo4** [comment]
Nextjs does not seem to come with pre and post build hook like something from Astro. But I guess I can add scripts that run after the build using package managers and put them in the right place. Still not sure how will it bundle. I guess I have to explore this more.
